base_url = "https://sigmasd.github.io"
title = "sigmaSd"
description = "Blogging about random stuff"
author = "sigmaSd"
theme = "tabi"

compile_sass = true
build_search_index = true
generate_feeds = true

default_language = "en"
taxonomies = [{name = "tags", feed = true}]

[search]
index_format = "elasticlunr_json"

[link_checker]
external_level = "warn"

[markdown]
bottom_footnotes = true
smart_punctuation = true

[markdown.highlighting]
theme = "github-dark"
style = "inline"

[extra]
allowed_domains = [
    { directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
]
theme_switcher = true
default_theme = "dark"
skin = "teal"
copy_button = true
show_reading_time = true
show_date = true

menu = [
    { name = "Blog", url = "blog", trailing_slash = true },
    { name = "IRust Book", url = "irust_book", trailing_slash = true },
]

socials = [
    { name = "github", url = "https://github.com/sigmaSd", icon = "github" },
]

footer_menu = [
    {url = "https://github.com/sigmaSd/sigmaSd.github.io", name = "Source Code", trailing_slash = false},
]
